### ISSUE TITLE
Error in the structure of the ontology tree

### ISSUE THREAD

**Issue by dphilip** [enanomapper/ontologies#70]
There seems to be some error in the structure of the ontology tree. Despite all ontology browsers having the same version (3.0), they show different things. 

For example, the term "hierarchical clustering" belongs to different Parent classes and has different "neighbours" in these two locations:
http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.enanomapper.org%2Fonto%2FENM_0000009&jump_to_nav=true
http://aber-owl.net/ontology/ENM#!http%3A%2F%2Fpurl.enanomapper.org%2Fonto%2FENM_0000009

At the same time, in http://www.ebi.ac.uk/ols/ontologies/enm/individuals?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000755 there are other entries that contain hierarchical clustering but not "hierarchical clustering" alone.

**Comment by JKChang2015** [comment]
Hi Philip,

Thank you for your notice.  The problem caused by duplicated URIs conflict to the new terms. I re-assigned URIs for modelling terms from "http://purl.enanomapper.org/onto/ENM_0******* " to "http://purl.enanomapper.org/onto/ENM_8******* ". please check updated eNM ontology from.  http://purl.enanomapper.org/onto/enanomapper.owl

:)

**Comment by dphilip** [comment]
Hi Jia, 
I downloaded the owl file and checked locally. Many issues are fixed, but with a quick overview I noticed some discrepancies. For example:

- descriptor should be the parent class of chemical descriptor. they appear to belong to the same level.
- inside "descriptor" there is a reference to http://semanticscience.org/resource/CHEMINF_000123, which is "chemical descriptor", but is coded CHEMINF_000123. It should be "chemical descriptor" and include the others. Something must have not worked as planned I guess!
Will check more extensively as we proceed to the next release.
Thanks for the work!

**Comment by JKChang2015** [comment]
Hi Philp,

1. I located **'descriptor'** as the parent class of **'chemical descriptor'**, i.e. [iris file](https://github.com/enanomapper/ontologies/blob/master/config/cheminf.iris#L7). 
**'Chemical descriptor'** is imported from Chemical Information Ontology (CHEMINF) which is  currently unable to load .  FYI:  #71 , it will be automatically fixed after cheminf.owl is ready to load. 

2. it has been fixed. 

Thank you!

**Comment by JKChang2015** [comment]
Hi Philip,

Our server still can't load Chemical Information Ontology and merge it to eNM ontology. I ran the slimming progress in my own computer and fixed the problem. Please check it. 

![descriptor](https://cloud.githubusercontent.com/assets/16242098/18289337/e7ff8880-7476-11e6-8a60-5ecdaeec3569.jpg)

Jia

**Comment by dphilip** [comment]
I gave it a quick check and it looks nice!
Thanks!
